CC_Flask/concepts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class ConceptForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Concept')

CC_Flask/engineerprofile/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from flask_login import current_user
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from CC_Flask.models import User


class EngineerprofileForm(FlaskForm):
    firstname = StringField('Firstname', validators=[DataRequired()])
    lastname = TextAreaField('Lastname', validators=[DataRequired()])
    uscitizen = StringField('Uscitizen', validators=[DataRequired()])
    github = StringField('Github', validators=[DataRequired()])
    linkedin = StringField('Linkedin', validators=[DataRequired()])
    personalsite = StringField('Personalsite', validators=[DataRequired()])
    reason = StringField('Reason', validators=[DataRequired()])
    experienceyrs = StringField('Experienceyrs', validators=[DataRequired()])
    languages = StringField('Languages', validators=[DataRequired()])
    interest = StringField('Interest', validators=[DataRequired()])
    blurb = StringField('Blurb', validators=[DataRequired()])

    submit = SubmitField('Engineerprofile')

class UpdateEngineerForm(FlaskForm):
    firstname = StringField('Firstname',
                           validators=[DataRequired(), Length(min=2, max=20)])
    lastname = StringField('Lastname',
                        validators=[DataRequired(), Email()])
    submit = SubmitField('Update')

CC_Flask/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

CC_Flask/concepts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from CC_Flask import db
from CC_Flask.models import Concept
from CC_Flask.concepts.forms import ConceptForm

concepts = Blueprint('concepts', __name__)


@concepts.route("/concept/new", methods=['GET', 'POST'])
@login_required
def new_concept():
    form = ConceptForm()
    if form.validate_on_submit():
        concept = Concept(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(concept)
        db.session.commit()
        flash('Your concept has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_concept.html', title='New concept',
                           form=form, legend='New concept')


@concepts.route("/concept/<int:concept_id>")
def concept(concept_id):
    concept = Concept.query.get_or_404(concept_id)
    return render_template('concept.html', title=concept.title, concept=concept)


@concepts.route("/concept/<int:concept_id>/update", methods=['GET', 'POST'])
@login_required
def update_concept(concept_id):
    concept = Concept.query.get_or_404(concept_id)
    if concept.author != current_user:
        abort(403)
    form = ConceptForm()
    if form.validate_on_submit():
        concept.title = form.title.data
        concept.content = form.content.data
        db.session.commit()
        flash('Your concept has been updated!', 'success')
        return redirect(url_for('concepts.concept', concept_id=concept.id))
    elif request.method == 'GET':
        form.title.data = concept.title
        form.content.data = concept.content
    return render_template('create_concept.html', title='Update Concept',
                           form=form, legend='Update Concept')


@concepts.route("/concept/<int:concept_id>/delete", methods=['POST'])
@login_required
def delete_concept(concept_id):
    concept = Concept.query.get_or_404(concept_id)
    if concept.author != current_user:
        abort(403)
    db.session.delete(concept)
    db.session.commit()
    flash('Your concept has been deleted!', 'success')
    return redirect(url_for('main.home'))

CC_Flask/engineerprofile/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from CC_Flask import db
from CC_Flask.models import Engineerprofile
from CC_Flask.engineerprofile.forms import EngineerprofileForm, UpdateEngineerForm

engineerprofiles = Blueprint('engineerprofiles', __name__)


@engineerprofiles.route("/engineerprofile/new", methods=['GET', 'POST'])
@login_required
def new_engineerprofile():
    form = EngineerprofileForm()
    if form.validate_on_submit():
        engineerprofile = Engineerprofile(firstname=form.firstname.data, lastname=form.lastname.data, uscitizen=form.uscitizen.data, github=form.github.data, linkedin=form.linkedin.data, personalsite=form.personalsite.data,
                                          reason=form.reason.data, experienceyrs=form.experienceyrs.data, languages=form.languages.data, interest=form.interest.data, blurb=form.blurb.data,
                                            author=current_user)
        db.session.add(engineerprofile)
        db.session.commit()
        flash('Your profile has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('engineersignup.html', title='Engineer Profile',
                           form=form, legend='Engineer Profile')


@engineerprofiles.route("/engineerprofile/<int:engineerprofile_id>")
def engineerprofile(engineerprofile_id):
    engineerprofile = Engineerprofile.query.get_or_404(engineerprofile_id)
    return render_template('engineerprofile.html',  firstname=engineerprofile.firstname, engineerprofile=engineerprofile, lastname=engineerprofile.lastname)


@engineerprofiles.route("/engineerprofile/<int:engineerprofile_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(engineerprofile_id):
    engineerprofile = Engineerprofile.query.get_or_404(engineerprofile_id)
    if engineerprofile.author != current_user:
        abort(403)
    form = EngineerprofileForm()
    if form.validate_on_submit():
        engineerprofile.firstname = form.firstname.data
        engineerprofile.lastname = form.lastname.data
        db.session.commit()
        flash('Your engineerprofile has been updated!', 'success')
        return redirect(url_for('engineerprofiles.engineerprofile', engineerprofile_id=engineerprofile.id))
    elif request.method == 'GET':
        form.firstname.data = engineerprofile.title
        form.lastname.data = engineerprofile.content
    return render_template('create_concept.html', title='Update Concept',
                           form=form, legend='Update Concept')


@engineerprofiles.route("/engineerprofile/<int:engineerprofile_id>/delete", methods=['POST'])
@login_required
def delete_engineerprofile(engineerprofile_id):
    engineerprofile = Engineerprofile.query.get_or_404(engineerprofile_id)
    if engineerprofile.author != current_user:
        abort(403)
    db.session.delete(engineerprofile)
    db.session.commit()
    flash('Your engineerprofile has been deleted!', 'success')
    return redirect(url_for('main.home'))

@engineerprofiles.route("/account/engineerinfo")
@login_required
def engineerinfo():
    form = UpdateEngineerForm()
    if form.validate_on_submit():
        current_user.firstname = form.firstname.data
        current_user.lastname = form.lastname.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.firstname.data = current_user.firstname
        form.lastname.data = current_user.lastname
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('engineerinfo.html', title='Account',
                           image_file=image_file, form=form)

CC_Flask/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from CC_Flask import db, bcrypt
from CC_Flask.models import User, Concept, Engineerprofile
from CC_Flask.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from CC_Flask.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('users.feed'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('users.feed'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_concepts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    concepts = Concept.query.filter_by(author=user)\
        .order_by(Concept.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_concepts.html', concepts=concepts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

@users.route("/engineerfeed")
@login_required
def feed():
    page = request.args.get('page', 1, type=int)
    engineerprofiles = Engineerprofile.query.order_by(Engineerprofile.experienceyrs.desc()).paginate(page=page, per_page=5)
    return render_template('engineerfeed.html', engineerprofiles=engineerprofiles)

@users.route("/conceptsfeed")
@login_required
def conceptsfeed():
    page = request.args.get('page', 1, type=int)
    concepts = Concept.query.order_by(Concept.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('conceptsfeed.html', concepts=concepts)

CC_Flask/templates/about.html
{% extends "layout.html" %}
{% block content %}
  <div class="card px-1">
    <img class="card-img-top" src="./static/profile_pics/default.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">James Lenahan - Founder</h5>
      <p class="card-text">A salesperson turned software engineer, James has spent his career yearning to start a powerful and disruptive business. With the inception of Code Connect, he was able to translate both his extensive knowledge of the labor market and his newfound love and passion for software engineering into a service that will dramatically shift employment compensation from wage-based to equity-based in the digital world.</p>
    </div>
  </div>

  <div class="card px-1">
    <img class="card-img-top" src="./static/profile_pics/JWW.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Jennifer Orabona - Co-Founder</h5>
      <p class="card-text">JWW</p>
    </div>
  </div>
{% endblock content %}

CC_Flask/templates/concept.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + concept.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=concept.author.username) }}">{{ concept.author.username }}</a>
        <small class="text-muted">{{ concept.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if concept.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('concepts.update_concept', concept_id=concept.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ concept.title }}</h2>
      <p class="article-content">{{ concept.content }}</p>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete concept?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('concepts.delete_post', concept_id=concept.id) }}" method="post">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

CC_Flask/templates/conceptsfeed.html
{% extends "layout.html" %}
{% block content %}
    <h1> Concepts: </h1>
    {% for concept in concepts.items %}
        <article class="media content-section">

          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + concept.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">

              <a class="mr-2" href="{{ url_for('users.user_concepts', username=concept.author.username) }}">{{ concept.author.username }}</a>
              <small class="text-muted">{{ concept.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('concepts.concept', concept_id=concept.id) }}">{{ concept.title }}</a></h2>
            <p class="article-content">{{ concept.content }}</p>
          </div>
        </article>

    {% endfor %}
    {% for page_num in concepts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if concepts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}






<div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest concepts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>

CC_Flask/templates/contact.html
{% extends "layout.html" %}
{% block content %}
      <div class="container">
        <h1 class="display-4">Send emails to:</h1>
        <h2 class="lead">james.k.lenahan@gmail.com</h2>
      </div>

{% endblock content %}

CC_Flask/templates/create_concept.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">New Company Name</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

CC_Flask/templates/engineerprofile.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + concept.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_concepts', username=concept.author.username) }}">{{ concept.author.username }}</a>
        <small class="text-muted">{{ concept.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if concept.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('concepts.update_concept', concept_id=concept.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ concept.title }}</h2>
      <p class="article-content">{{ concept.content }}</p>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete concept?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('concepts.delete_concept', concept_id=concept.id) }}" method="post">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

CC_Flask/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <div class="jumbotron jumbotron-fluid bg-light">
      <div class="container">
        <h1 class="display-4">Code Connect</h1>
        <h2 class="lead">This is the best company idea ever.</h2>
      </div>
    </div>
            {% if current_user.is_authenticated %}
        <div class="card bg-light mt-75">
            <a type="button" class="btn btn-success" href="/account">
                Visit your Account
            </a>
        </div>

              {% else %}
        <div class="card bg-light mt-75">
            <a type="button" class="btn btn-success" href="/register">
                Get Started
            </a>
        </div>
              {% endif %}


{% endblock content %}

CC_Flask/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-success") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

CC_Flask/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}

CC_Flask/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

CC_Flask/templates/user_concepts.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">concepts by {{ user.username }} ({{ concepts.total }})</h1>
    {% for concept in concepts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + concept.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=concept.author.username) }}">{{ concept.author.username }}</a>
              <small class="text-muted">{{ concept.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('concepts.concept', concept_id=concept.id) }}">{{ concept.title }}</a></h2>
            <p class="article-content">{{ concept.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in concepts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if concepts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}